import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 p-4">
          <div className="container mx-auto flex justify-between items-center">
            <a href="/" className="text-white text-lg font-semibold"></a>
            <div className="hidden md:flex space-x-4">
              <a href="/performances" className="text-gray-300 hover:text-white">Performances</a>
              <a href="/singers" className="text-gray-300 hover:text-white">Singers</a>
              <a href="/conductors" className="text-gray-300 hover:text-white">Conductors</a>
              <a href="/choruses" className="text-gray-300 hover:text-white">Chors</a>
              <a href="/orchestras" className="text-gray-300 hover:text-white">Orchestras</a>
              <a href="/composers" className="text-gray-300 hover:text-white">Composers</a>
              <a href="/venues" className="text-gray-300 hover:text-white">Venues</a>
            </div>
            <div className="md:hidden">
              <button className="text-gray-300 hover:text-white focus:outline-none">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h16m-7 6h7"></path>
                </svg>
              </button>
            </div>
          </div>
        </nav>
        <div className="p-8">
          {children}
        </div>
      </body>
    </html>
  );
}
